// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oapisolirzbgqdopqghx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hcGlzb2xpcnpiZ3Fkb3BxZ2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDAyMzcsImV4cCI6MjA2NTYxNjIzN30.LrmT9o8TMH-OlHT-T2Luybzn5uxvk1NjV9EoBrfHP8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);